name: Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:
  
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
      -
        name: Checkout 
        uses: actions/checkout@master
      -
        name: Kubectl_awscli
        run: |
         curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
         sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
         kubectl version --client
         sudo apt-get install unzip
         curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
         unzip awscliv2.zip
         
      -
         name: aws
         run: |
          aws --version
          aws eks --region us-east-1 update-kubeconfig --name KuberCluster
          
      -
         name: deploy
         run: |
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
          kubectl apply -f k8-lb-hpa-pod/lb.yml
          kubectl apply -f k8-lb-hpa-pod/hpa.yml
          kubectl apply -f k8-lb-hpa-pod/deployment_ngnix.yml
